backend:
  name: github
  repo: aliblackwell/jamstack-starter # Path to your GitHub repository
media_folder: "website/img" 
public_folder: "/img" 
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Services Page"
        name: "services"
        file: "website/pages/services/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
