backend:
  name: github
  squash_merges: true
  repo: gwenhustwit/gwenhustwit.com # Path to your GitHub repository

# when using the default proxy server port
local_backend: true
# local_backend:
#   # when using a custom proxy server port
#   url: http://localhost:8082/api/v1
#   # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
#   allowed_hosts: ['192.168.0.1']

media_folder: "website/img"
public_folder: "/img"
collections:
  - label: "Core Options"
    name: "options"
    files:
      - label: Meta info and content
        name: meta
        file: "website/_data/meta.json"
        fields:
          - label: Site Title
            name: siteTitle
            widget: string
          - label: Site slogan
            name: siteSlogan
            widget: string
            hint: Used as default share text when site is shared
          - label: Site URL
            name: siteUrl
            widget: string
            hint: Used as share URL
          - label: Favicon
            hint: The "favourites icon" that appears in the tab next to the title
            widget: image
            name: favicon
      - label: "Header and navigation options"
        name: "options"
        file: "website/_data/options.json"
        fields:
          - label: Logo
            hint: Please choose a logo
            name: logo
            widget: "image"
          - label: Logo alignment
            hint: Where would you like your logo to appear?
            name: logoAlign
            widget: "select"
            options:
              - label: "Align centre"
                value: "centre"
              - label: "Align left"
                value: "left"
          - label: Nav style
            hint: What colour would you like behind your nav?
            name: navStyle
            widget: "select"
            default: "primary-bg"
            options:
              - label: Standard
                value: standard-bg
              - label: Primary
                value: primary-bg
              - label: Secondary
                value: secondary-bg
              - label: Contrast
                value: contrast-bg
          - label: Footer style
            hint: What colour would you like behind your nav?
            name: footerStyle
            widget: "select"
            default: "secondary-bg"
            options:
              - label: Standard
                value: standard-bg
              - label: Primary
                value: primary-bg
              - label: Secondary
                value: secondary-bg
              - label: Contrast
                value: contrast-bg

          - label: Primary menu mobile format
            hint: On mobile, what should happen to your primary menu?
            name: menuStyle
            widget: "select"
            options:
              - label: "Hamburger Menu - I have a long menu and it just won't fit on mobile (not recommended)"
                value: "burger"
              - label: "Move to bottom - It's closer to my user's thumbs and they can see all the options immediately. (recommended)"
                value: "bottom"
          - label: Always hamburger or just on mobile?
            hint: If you've chosen a hamburger menu, do you want it to appear the whole time, or only on mobile?
            name: showBurger
            widget: "select"
            options:
              - label: "Never show my menu items without a click (not recommended)"
                value: "always"
              - label: "Only use the hamburger for mobile users (recommended)"
                value: "mobile"
          - label: Parent/child navs
            hint: Use this section combined with page navigation options to create child menus
            name: childNavs
            widget: list
            summary: "Parent/child nav: {{fields.name}}"
            fields:
              - {
                  label: Title of parent page,
                  name: name,
                  hint: What is the currently set title of the parent page? N.B. If you change the page's title in future you must update this menu.,
                  widget: string,
                  default: Services,
                }
              - {
                  label: Permalink of parent page,
                  name: path,
                  hint: Must include opening and closing '/',
                  default: "/services/",
                }
              - {
                  label: Menu label,
                  name: label,
                  hint: What appears above the child menu? Most likely the name of the parent page,
                  default: Services,
                }
              - label: Child item permalinks
                name: children
                hint: We need to know the permalinks of children so we can highlight the parent nav when a user is on a child page. Comma-separated list of permalinks
                default: /service-one/, /service-two/
                widget: list

  # Pages
  - name: "pages"
    label: "Pages"
    folder: "website/starter-pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Show title?, name: showTitle, widget: boolean, default: true }
      - {
          label: permalink,
          name: permalink,
          widget: string,
          hint: "Must include / at beginning and end e.g. /privacy/",
        }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Navigation label", name: "key", widget: "string" }
          - label: Navigation location
            hint: Which menu should this page appear in?
            name: parent
            widget: "select"
            options:
              - label: "Primary menu. Defaults top-left."
                value: "Primary"
              - label: "Secondary menu. Defaults top-right."
                value: "Secondary"
              - label: "Footer menu"
                value: "Footer"
              - label: "Don't show in site menus."
                value: "none"
              - label: "Show in child menu"
                hint: "If you want to show this in child menu, add the parent page's title in the field below, then save and head to Options and add this page's permalink to the desired menu"
                value: "About"
          - {
              label: "Parent menu item",
              name: "parent",
              widget: "string",
              hint: Add e.g. Services or About to make this page a child of those pages. To add it to the menu,
              head to Options and add this page's permalink to the desired menu.,
              requred: false,
            }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - &dynamicContent
        label: Content
        name: dynamicContent
        widget: "list"
        types:
          - label: Two-up text CTAs
            summary: Two-up text CTAs
            name: textCTAs
            widget: list
            fields:
              - &bg
                label: Background Colour
                name: bg
                widget: select
                default: standard-bg
                options:
                  - label: Standard
                    value: standard-bg
                  - label: Primary
                    value: primary-bg-tint
                  - label: Secondary
                    value: secondary-bg-tint
                  - label: Contrast
                    value: contrast-bg
              - label: Items
                name: ctaItems
                widget: list
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Blurb, name: blurb, widget: text }
                  - {
                      label: Button Label,
                      name: label,
                      widget: string,
                      required: false,
                    }
                  - { label: URL, name: url, widget: string, required: false }
          - label: Free Content Section
            summary: Free Content Section
            name: freeContent
            widget: list
            fields:
              - *bg
              - { label: Content, name: content, widget: markdown }
          - label: Gallery
            name: gallery
            widget: list
            summary: Gallery
            fields:
              - *bg
              - label: "Items"
                name: "galleryItems"
                widget: "list"
                fields:
                  - { label: Url, name: url, widget: string, required: false }
                  - {
                      label: Description,
                      name: description,
                      widget: text,
                      required: false,
                    }
                  - {
                      label: "Image Attribution",
                      name: attribution,
                      widget: string,
                      required: false,
                    }
                  - { label: Image alt text, name: alt, widget: text }
                  - {
                      label: Image,
                      name: image,
                      widget: image,
                      default: "/img/holding.jpg",
                    }
          - label: Text with image
            name: textWithImage
            widget: list
            summary: "Text with Image: {{fields.firstPara}}"
            fields:
              - *bg
              - {
                  label: "Opening paragraph (bigger)",
                  name: firstPara,
                  widget: text,
                }
              - { label: "Image", name: "image", widget: image }
              - { label: "Image Alt", name: "alt", widget: string }
              - { label: "Free Content", name: "content", widget: markdown }
          - label: Cards
            name: cardsList
            widget: "list"
            summary: "Cards: {{fields.title}}"
            fields:
              - *bg
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  required: false,
                }
              - label: "Layout"
                name: "layout"
                widget: "select"
                options:
                  - label: "Full wide"
                    value: "fullWide"
                  - label: "Three up"
                    value: "threeUp"
              - label: "Cards"
                name: "cards"
                widget: "list"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: string
                  - label: "Text"
                    name: "text"
                    widget: "text"
                  - label: "SVG"
                    name: "svg"
                    required: false
                    widget: string
                    hint: The filename excluding extension of an SVG inside website/_includes/undraw-illustrations e.g. undraw_gdpr_3xfb
                  - label: "Image"
                    name: img
                    widget: image
                    hint: Choose either an SVG or an image
                    required: false
                  - label: "Label"
                    name: label
                    widget: string
                    hint: CTA text
                    required: false
                  - label: "URL"
                    name: url
                    widget: string
                    hint: CTA URL
                    required: false
          - label: Testimonial
            name: testimonial
            widget: "list"
            summary: "Testimonial by {{fields.author.name}}"
            fields:
              - *bg
              - {
                  label: Testimonial,
                  name: testimonial,
                  widget: string,
                  default: "Everything is awesome!",
                }
              - label: Author
                name: author
                widget: object
                fields:
                  - { label: Name, name: name, widget: string, required: true }
                  - {
                      label: Avatar,
                      name: avatar,
                      widget: image,
                      required: false,
                    }
          - label: Sharer
            name: sharer
            widget: "list"
            summary: "Sharer Active - {{fields.sharerType}}"
            fields:
              - *bg
              - label: Show sharer
                hint: Do you want to display a sharing component?
                name: sharerType
                widget: "select"
                options:
                  - label: "Full-width"
                    value: "fullWidth"
                  - label: "Button sharer"
                    value: "buttonSharer"
                  - label: "None"
                    value: "none"
          - label: Form
            name: form
            widget: "list"
            summary: "Form Active - {{fields.formName}}"
            fields:
              - *bg
              - {
                  label: Form Name,
                  name: formName,
                  widget: string,
                  default: "Contact",
                }
              - {
                  label: Success Message,
                  name: formSuccessMessage,
                  widget: string,
                  default: "Thank you for getting in touch. We will respond soon.",
                }
              - label: Fields
                name: fields
                widget: "list"
                summary: "{{fields.fieldType}} - {{fields.inputLabel}}"
                fields:
                  - {
                      label: Input Label,
                      name: inputLabel,
                      widget: string,
                      hint: "e.g. 'Your name' or 'Your email'",
                    }
                  - label: Field
                    name: fieldType
                    hint: "What type of input would you like?"
                    widget: "select"
                    options:
                      - label: "Email"
                        value: "inputEmail"
                      - label: "Text"
                        value: "inputText"
                      - label: "Long Text"
                        value: "textarea"
                      - label: "Number"
                        value: "inputNumber"
