backend:
  name: github
  repo: aliblackwell/jamstack-starter # Path to your GitHub repository

# when using the default proxy server port
local_backend: true
# local_backend:
#   # when using a custom proxy server port
#   url: http://localhost:8082/api/v1
#   # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
#   allowed_hosts: ['192.168.0.1']

media_folder: "website/img" 
public_folder: "/img" 
collections:
  - label: "Core Options"
    name: "options"
    files:
      - label: "Header and navigation options"
        name: "options"
        file: "website/_data/options.json"
        fields:
          - label: Logo alignment
            hint: Where would you like your logo to appear?
            name: logo
            widget: "select"            
            options: 
              - label: "Align centre"
                value: "centre"
              - label: "Align left"
                value: "left"
          - label: Primary menu mobile format 
            hint: On mobile, what should happen to your primary menu?
            name: menuStyle
            widget: "select"
            options: 
              - label: "Hamburger Menu - I have a long menu and it just won't fit on mobile (not recommended)"
                value: "burger"
              - label: "Move to bottom - It's closer to my user's thumbs and they can see all the options immediately. (recommended)"
                value: "bottom"
          - label: Always hamburger or just on mobile?
            hint: If you've chosen a hamburger menu, do you want it to appear the whole time, or only on mobile?
            name: showBurger
            widget: "select"
            options: 
              - label: "Never show my menu items without a click (not recommended)"
                value: "always"
              - label: "Only use the hamburger for mobile users (recommended)"
                value: "mobile"
  - label: "Pages"
    name: "pages"
    files:
      - label: "Services Page"
        name: "services"
        file: "website/pages/services/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}

  # Our pages e.g. About
  - name: "services"
    label: "Services"
    folder: "website/pages/services"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Navigation label", name: "key", widget: "string"}
          - { label: "Parent", name: "parent", widget: "string", default: "Services"  }          
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }
